# Generated by Django 2.2.10 on 2022-06-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
    ]
