# Generated by Django 2.2.10 on 2022-06-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_api', '0004_auto_20220614_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
